/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__ci_fix__0_0_1 = never;
export type PromptConfig__ci_fix__0_0_1 = {
  models: ['openrouter/free'];
  temperature: number;
};
export type PromptVersion__ci_fix__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__ci_fix__0_0_1;
  variables: PromptVariables__ci_fix__0_0_1;
  content: string;
};
export type Prompt__ci_fix = {
  name: 'CI fix ';
  slug: 'ci-fix';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__ci_fix__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    'ci-fix': Prompt__ci_fix;
  };
  globals: Globals;
};
